stages:
  - build
  - test
  # - package
  # - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  CONTAINER_NAME : "noori-api-1"
  TEST_CONTAINER_NAME: "noori-test"
  TEST_PORT: "8080"

cache:
  paths:
    - .m2/repository/

install:
  image: maven:latest
  stage: build
  script:
    - echo "$CI_REGISTRY_USER - - -  $CI_JOB_TOKEN - - - $CI_REGISTRY"
    - echo "Installing the project..."
    - mvn clean install -DskipTests
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)\/.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

test:
    image: maven:latest
    stage: test
    script:
        - echo "Running tests..."
        - mvn test -DskipTests=false
    dependencies:
      - install
    rules:
        - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)\/.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

# package:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   stage: package
#   script:
#     - echo "Logging into GitLab Container Registry..."
#     - echo "$CI_REGISTRY_PASSWORD" |  docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
#     - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA -f docker/Dockerfile .
#     - docker save $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA -o noori-api.tar
#     - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
#     - docker images
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null
#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)\/.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

# deploy:
#   stage: deploy
#   image: alpine:latest
#   variables:
#     SERVER: "$EC2_USER@$EC2_HOST"
#   before_script:
#     - apk add --no-cache openssh
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
#     - chmod 600 /tmp/id_rsa
#     - eval $(ssh-agent -s)
#     - ssh-add /tmp/id_rsa
#     - mkdir -p ~/.ssh
#     - ssh-keyscan "$EC2_HOST" >> ~/.ssh/known_hosts
#   script:
#     - ssh "$SERVER" "echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY"
#     - ssh "$SERVER" "docker pull $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
#     # - IMAGE_TAG=$(echo "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" | sed 's/[&/\]/\\&/g')
#     # - ssh "$SERVER" "sed -i 's/^APP_IMAGE=.*/APP_IMAGE=$IMAGE_TAG/' /home/ec2-user/noori-back/.env"
#     # - ssh "$SERVER" "docker-compose -f /home/ec2-user/noori-back/docker-compose.yml up -d"
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null
#     - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)\/.*$/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

