version: '3.8'

services:
  postgres:
    image: postgres:14.10-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network

  alten-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alten-backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: on-failure
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - alten-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge